//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Packages/com.unity.xr.rayneo.openxr/SDK/Runtime/Scripts/Comps/Inputs/Actions/RayNeoInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Packages/com.unity.xr.rayneo.openxr/SDK/Runtime/Scripts/Comps/Inputs/Actions/RayNeoInput.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @RayNeoInput: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @RayNeoInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RayNeoInput"",
    ""maps"": [
        {
            ""name"": ""SimpleTouch"",
            ""id"": ""3ee82658-13e9-43a1-b803-5c00561e5f49"",
            ""actions"": [
                {
                    ""name"": ""Tap"",
                    ""type"": ""Button"",
                    ""id"": ""f65f1bc0-5c7c-4d25-ae46-f4ead2976053"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""7d789459-0fa4-4d1e-b14d-6a2885d3252a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""PassThrough"",
                    ""id"": ""46cc4698-f59d-4059-bb8e-9c201ad1ffae"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""29130e4c-b31c-4a56-b73a-096bbf7c1465"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4fb838e-cafc-48b5-a432-40ac4e7124cd"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4537a551-5f67-4c59-9af4-39f5e22c4d32"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a3cfdba-4b0a-46fe-8ae9-8af1ee59d297"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""786c51c8-605f-48d5-b9d7-cf09f1a41335"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72efd082-c0a5-4374-b7dd-8f51c71c2cd3"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MulitTouch"",
            ""id"": ""af95e208-2af8-4d85-9f62-874579f250d7"",
            ""actions"": [
                {
                    ""name"": ""Touch1Tap"",
                    ""type"": ""Button"",
                    ""id"": ""06fa4ec7-69ab-4248-abb6-7ca41bdb441a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch2Tap"",
                    ""type"": ""Button"",
                    ""id"": ""3b56ea4f-927c-441e-ae4b-824df2788a26"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch1Position"",
                    ""type"": ""Value"",
                    ""id"": ""db7d0187-b036-4b42-9dd7-ab618a1a13e5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch2Position"",
                    ""type"": ""Value"",
                    ""id"": ""69a93738-7988-492d-aee3-813513fad189"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Touch1Press"",
                    ""type"": ""Button"",
                    ""id"": ""86fdf3ae-2b73-4451-a0ea-e44a759115ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Touch2Press"",
                    ""type"": ""Button"",
                    ""id"": ""4d7cf9a9-1987-4413-a5c6-79b55c4d5490"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ce37cee0-3fee-470f-b68f-d2f57535eb05"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""442e3399-790f-46f1-84c3-c15509b47cac"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93482bb4-5a0b-4985-8585-6182befe3153"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b5ba651c-40ca-44ba-ab7c-45b223c7446d"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9212e8c4-1c08-4fff-95c1-7ac30d0c6293"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""97b6e302-70fc-4668-b9af-51803c1edf9f"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch1Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5cd560f7-775b-4703-ac97-0b65d23a6299"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62ec8d1b-5b63-4a5e-9a99-dfea4cebd831"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09eaf8e1-7e83-452a-b443-04ebd8cc997f"",
                    ""path"": ""<Touchscreen>/touch1/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Touch2Tap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Ring"",
            ""id"": ""982be9de-2fc3-4ab5-868b-3e53b23ec25b"",
            ""actions"": [
                {
                    ""name"": ""XRPose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""33cefc00-2bd8-42c4-8414-5be7577e6822"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchPadClick"",
                    ""type"": ""Button"",
                    ""id"": ""a82eefa0-23f6-4b3c-831d-36615c5f673c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""HeavyClick"",
                    ""type"": ""Button"",
                    ""id"": ""26ede634-498a-4303-8dbe-764200305db4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6d4e4618-1ba6-4cde-958a-2be467a89265"",
                    ""expectedControlType"": ""Quaternion"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Position"",
                    ""type"": ""PassThrough"",
                    ""id"": ""75c5dd53-87a8-4afd-883f-102a8d83b423"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89321d41-b63a-47a8-b787-a665f09e5785"",
                    ""path"": ""<RayNeoRingController>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XRPose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""74d8e7b8-419c-46dc-b6d1-7dcf9ac5386a"",
                    ""path"": ""<RingInputDevice>/button_touch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPadClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""817dae67-749c-4909-9f49-d61b1b565677"",
                    ""path"": ""<RingInputDevice>/button_heavy"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b0bc7fbf-75a0-4244-9fb8-ac89f17a727e"",
                    ""path"": ""<RayNeoRingController>/homeButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""HeavyClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e29aad5e-5708-4e16-8329-1999fed88b28"",
                    ""path"": ""<RingInputDevice>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82ad01de-e7ce-4a55-869c-2ed650c19c01"",
                    ""path"": ""<RingInputDevice>/touchPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""CellPhone"",
            ""id"": ""c19b0352-7d2b-403d-ab29-7bbfdcfc782e"",
            ""actions"": [
                {
                    ""name"": ""Pose"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b148c107-5c45-444b-a1df-d9e3506ec2ef"",
                    ""expectedControlType"": ""Pose"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""504a76bb-c72a-4156-8723-909fe8312086"",
                    ""path"": ""<RayNeoCellPhoneController>/devicePose"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pose"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // SimpleTouch
        m_SimpleTouch = asset.FindActionMap("SimpleTouch", throwIfNotFound: true);
        m_SimpleTouch_Tap = m_SimpleTouch.FindAction("Tap", throwIfNotFound: true);
        m_SimpleTouch_Position = m_SimpleTouch.FindAction("Position", throwIfNotFound: true);
        m_SimpleTouch_Press = m_SimpleTouch.FindAction("Press", throwIfNotFound: true);
        // MulitTouch
        m_MulitTouch = asset.FindActionMap("MulitTouch", throwIfNotFound: true);
        m_MulitTouch_Touch1Tap = m_MulitTouch.FindAction("Touch1Tap", throwIfNotFound: true);
        m_MulitTouch_Touch2Tap = m_MulitTouch.FindAction("Touch2Tap", throwIfNotFound: true);
        m_MulitTouch_Touch1Position = m_MulitTouch.FindAction("Touch1Position", throwIfNotFound: true);
        m_MulitTouch_Touch2Position = m_MulitTouch.FindAction("Touch2Position", throwIfNotFound: true);
        m_MulitTouch_Touch1Press = m_MulitTouch.FindAction("Touch1Press", throwIfNotFound: true);
        m_MulitTouch_Touch2Press = m_MulitTouch.FindAction("Touch2Press", throwIfNotFound: true);
        // Ring
        m_Ring = asset.FindActionMap("Ring", throwIfNotFound: true);
        m_Ring_XRPose = m_Ring.FindAction("XRPose", throwIfNotFound: true);
        m_Ring_TouchPadClick = m_Ring.FindAction("TouchPadClick", throwIfNotFound: true);
        m_Ring_HeavyClick = m_Ring.FindAction("HeavyClick", throwIfNotFound: true);
        m_Ring_Rotation = m_Ring.FindAction("Rotation", throwIfNotFound: true);
        m_Ring_Position = m_Ring.FindAction("Position", throwIfNotFound: true);
        // CellPhone
        m_CellPhone = asset.FindActionMap("CellPhone", throwIfNotFound: true);
        m_CellPhone_Pose = m_CellPhone.FindAction("Pose", throwIfNotFound: true);
    }

    ~@RayNeoInput()
    {
        UnityEngine.Debug.Assert(!m_SimpleTouch.enabled, "This will cause a leak and performance issues, RayNeoInput.SimpleTouch.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MulitTouch.enabled, "This will cause a leak and performance issues, RayNeoInput.MulitTouch.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Ring.enabled, "This will cause a leak and performance issues, RayNeoInput.Ring.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_CellPhone.enabled, "This will cause a leak and performance issues, RayNeoInput.CellPhone.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // SimpleTouch
    private readonly InputActionMap m_SimpleTouch;
    private List<ISimpleTouchActions> m_SimpleTouchActionsCallbackInterfaces = new List<ISimpleTouchActions>();
    private readonly InputAction m_SimpleTouch_Tap;
    private readonly InputAction m_SimpleTouch_Position;
    private readonly InputAction m_SimpleTouch_Press;
    /// <summary>
    /// Provides access to input actions defined in input action map "SimpleTouch".
    /// </summary>
    public struct SimpleTouchActions
    {
        private @RayNeoInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SimpleTouchActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "SimpleTouch/Tap".
        /// </summary>
        public InputAction @Tap => m_Wrapper.m_SimpleTouch_Tap;
        /// <summary>
        /// Provides access to the underlying input action "SimpleTouch/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_SimpleTouch_Position;
        /// <summary>
        /// Provides access to the underlying input action "SimpleTouch/Press".
        /// </summary>
        public InputAction @Press => m_Wrapper.m_SimpleTouch_Press;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_SimpleTouch; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SimpleTouchActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SimpleTouchActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SimpleTouchActions" />
        public void AddCallbacks(ISimpleTouchActions instance)
        {
            if (instance == null || m_Wrapper.m_SimpleTouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SimpleTouchActionsCallbackInterfaces.Add(instance);
            @Tap.started += instance.OnTap;
            @Tap.performed += instance.OnTap;
            @Tap.canceled += instance.OnTap;
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
            @Press.started += instance.OnPress;
            @Press.performed += instance.OnPress;
            @Press.canceled += instance.OnPress;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SimpleTouchActions" />
        private void UnregisterCallbacks(ISimpleTouchActions instance)
        {
            @Tap.started -= instance.OnTap;
            @Tap.performed -= instance.OnTap;
            @Tap.canceled -= instance.OnTap;
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
            @Press.started -= instance.OnPress;
            @Press.performed -= instance.OnPress;
            @Press.canceled -= instance.OnPress;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SimpleTouchActions.UnregisterCallbacks(ISimpleTouchActions)" />.
        /// </summary>
        /// <seealso cref="SimpleTouchActions.UnregisterCallbacks(ISimpleTouchActions)" />
        public void RemoveCallbacks(ISimpleTouchActions instance)
        {
            if (m_Wrapper.m_SimpleTouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SimpleTouchActions.AddCallbacks(ISimpleTouchActions)" />
        /// <seealso cref="SimpleTouchActions.RemoveCallbacks(ISimpleTouchActions)" />
        /// <seealso cref="SimpleTouchActions.UnregisterCallbacks(ISimpleTouchActions)" />
        public void SetCallbacks(ISimpleTouchActions instance)
        {
            foreach (var item in m_Wrapper.m_SimpleTouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SimpleTouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SimpleTouchActions" /> instance referencing this action map.
    /// </summary>
    public SimpleTouchActions @SimpleTouch => new SimpleTouchActions(this);

    // MulitTouch
    private readonly InputActionMap m_MulitTouch;
    private List<IMulitTouchActions> m_MulitTouchActionsCallbackInterfaces = new List<IMulitTouchActions>();
    private readonly InputAction m_MulitTouch_Touch1Tap;
    private readonly InputAction m_MulitTouch_Touch2Tap;
    private readonly InputAction m_MulitTouch_Touch1Position;
    private readonly InputAction m_MulitTouch_Touch2Position;
    private readonly InputAction m_MulitTouch_Touch1Press;
    private readonly InputAction m_MulitTouch_Touch2Press;
    /// <summary>
    /// Provides access to input actions defined in input action map "MulitTouch".
    /// </summary>
    public struct MulitTouchActions
    {
        private @RayNeoInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public MulitTouchActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch1Tap".
        /// </summary>
        public InputAction @Touch1Tap => m_Wrapper.m_MulitTouch_Touch1Tap;
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch2Tap".
        /// </summary>
        public InputAction @Touch2Tap => m_Wrapper.m_MulitTouch_Touch2Tap;
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch1Position".
        /// </summary>
        public InputAction @Touch1Position => m_Wrapper.m_MulitTouch_Touch1Position;
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch2Position".
        /// </summary>
        public InputAction @Touch2Position => m_Wrapper.m_MulitTouch_Touch2Position;
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch1Press".
        /// </summary>
        public InputAction @Touch1Press => m_Wrapper.m_MulitTouch_Touch1Press;
        /// <summary>
        /// Provides access to the underlying input action "MulitTouch/Touch2Press".
        /// </summary>
        public InputAction @Touch2Press => m_Wrapper.m_MulitTouch_Touch2Press;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_MulitTouch; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="MulitTouchActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(MulitTouchActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="MulitTouchActions" />
        public void AddCallbacks(IMulitTouchActions instance)
        {
            if (instance == null || m_Wrapper.m_MulitTouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MulitTouchActionsCallbackInterfaces.Add(instance);
            @Touch1Tap.started += instance.OnTouch1Tap;
            @Touch1Tap.performed += instance.OnTouch1Tap;
            @Touch1Tap.canceled += instance.OnTouch1Tap;
            @Touch2Tap.started += instance.OnTouch2Tap;
            @Touch2Tap.performed += instance.OnTouch2Tap;
            @Touch2Tap.canceled += instance.OnTouch2Tap;
            @Touch1Position.started += instance.OnTouch1Position;
            @Touch1Position.performed += instance.OnTouch1Position;
            @Touch1Position.canceled += instance.OnTouch1Position;
            @Touch2Position.started += instance.OnTouch2Position;
            @Touch2Position.performed += instance.OnTouch2Position;
            @Touch2Position.canceled += instance.OnTouch2Position;
            @Touch1Press.started += instance.OnTouch1Press;
            @Touch1Press.performed += instance.OnTouch1Press;
            @Touch1Press.canceled += instance.OnTouch1Press;
            @Touch2Press.started += instance.OnTouch2Press;
            @Touch2Press.performed += instance.OnTouch2Press;
            @Touch2Press.canceled += instance.OnTouch2Press;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="MulitTouchActions" />
        private void UnregisterCallbacks(IMulitTouchActions instance)
        {
            @Touch1Tap.started -= instance.OnTouch1Tap;
            @Touch1Tap.performed -= instance.OnTouch1Tap;
            @Touch1Tap.canceled -= instance.OnTouch1Tap;
            @Touch2Tap.started -= instance.OnTouch2Tap;
            @Touch2Tap.performed -= instance.OnTouch2Tap;
            @Touch2Tap.canceled -= instance.OnTouch2Tap;
            @Touch1Position.started -= instance.OnTouch1Position;
            @Touch1Position.performed -= instance.OnTouch1Position;
            @Touch1Position.canceled -= instance.OnTouch1Position;
            @Touch2Position.started -= instance.OnTouch2Position;
            @Touch2Position.performed -= instance.OnTouch2Position;
            @Touch2Position.canceled -= instance.OnTouch2Position;
            @Touch1Press.started -= instance.OnTouch1Press;
            @Touch1Press.performed -= instance.OnTouch1Press;
            @Touch1Press.canceled -= instance.OnTouch1Press;
            @Touch2Press.started -= instance.OnTouch2Press;
            @Touch2Press.performed -= instance.OnTouch2Press;
            @Touch2Press.canceled -= instance.OnTouch2Press;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="MulitTouchActions.UnregisterCallbacks(IMulitTouchActions)" />.
        /// </summary>
        /// <seealso cref="MulitTouchActions.UnregisterCallbacks(IMulitTouchActions)" />
        public void RemoveCallbacks(IMulitTouchActions instance)
        {
            if (m_Wrapper.m_MulitTouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="MulitTouchActions.AddCallbacks(IMulitTouchActions)" />
        /// <seealso cref="MulitTouchActions.RemoveCallbacks(IMulitTouchActions)" />
        /// <seealso cref="MulitTouchActions.UnregisterCallbacks(IMulitTouchActions)" />
        public void SetCallbacks(IMulitTouchActions instance)
        {
            foreach (var item in m_Wrapper.m_MulitTouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MulitTouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="MulitTouchActions" /> instance referencing this action map.
    /// </summary>
    public MulitTouchActions @MulitTouch => new MulitTouchActions(this);

    // Ring
    private readonly InputActionMap m_Ring;
    private List<IRingActions> m_RingActionsCallbackInterfaces = new List<IRingActions>();
    private readonly InputAction m_Ring_XRPose;
    private readonly InputAction m_Ring_TouchPadClick;
    private readonly InputAction m_Ring_HeavyClick;
    private readonly InputAction m_Ring_Rotation;
    private readonly InputAction m_Ring_Position;
    /// <summary>
    /// Provides access to input actions defined in input action map "Ring".
    /// </summary>
    public struct RingActions
    {
        private @RayNeoInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public RingActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Ring/XRPose".
        /// </summary>
        public InputAction @XRPose => m_Wrapper.m_Ring_XRPose;
        /// <summary>
        /// Provides access to the underlying input action "Ring/TouchPadClick".
        /// </summary>
        public InputAction @TouchPadClick => m_Wrapper.m_Ring_TouchPadClick;
        /// <summary>
        /// Provides access to the underlying input action "Ring/HeavyClick".
        /// </summary>
        public InputAction @HeavyClick => m_Wrapper.m_Ring_HeavyClick;
        /// <summary>
        /// Provides access to the underlying input action "Ring/Rotation".
        /// </summary>
        public InputAction @Rotation => m_Wrapper.m_Ring_Rotation;
        /// <summary>
        /// Provides access to the underlying input action "Ring/Position".
        /// </summary>
        public InputAction @Position => m_Wrapper.m_Ring_Position;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Ring; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="RingActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(RingActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="RingActions" />
        public void AddCallbacks(IRingActions instance)
        {
            if (instance == null || m_Wrapper.m_RingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_RingActionsCallbackInterfaces.Add(instance);
            @XRPose.started += instance.OnXRPose;
            @XRPose.performed += instance.OnXRPose;
            @XRPose.canceled += instance.OnXRPose;
            @TouchPadClick.started += instance.OnTouchPadClick;
            @TouchPadClick.performed += instance.OnTouchPadClick;
            @TouchPadClick.canceled += instance.OnTouchPadClick;
            @HeavyClick.started += instance.OnHeavyClick;
            @HeavyClick.performed += instance.OnHeavyClick;
            @HeavyClick.canceled += instance.OnHeavyClick;
            @Rotation.started += instance.OnRotation;
            @Rotation.performed += instance.OnRotation;
            @Rotation.canceled += instance.OnRotation;
            @Position.started += instance.OnPosition;
            @Position.performed += instance.OnPosition;
            @Position.canceled += instance.OnPosition;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="RingActions" />
        private void UnregisterCallbacks(IRingActions instance)
        {
            @XRPose.started -= instance.OnXRPose;
            @XRPose.performed -= instance.OnXRPose;
            @XRPose.canceled -= instance.OnXRPose;
            @TouchPadClick.started -= instance.OnTouchPadClick;
            @TouchPadClick.performed -= instance.OnTouchPadClick;
            @TouchPadClick.canceled -= instance.OnTouchPadClick;
            @HeavyClick.started -= instance.OnHeavyClick;
            @HeavyClick.performed -= instance.OnHeavyClick;
            @HeavyClick.canceled -= instance.OnHeavyClick;
            @Rotation.started -= instance.OnRotation;
            @Rotation.performed -= instance.OnRotation;
            @Rotation.canceled -= instance.OnRotation;
            @Position.started -= instance.OnPosition;
            @Position.performed -= instance.OnPosition;
            @Position.canceled -= instance.OnPosition;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="RingActions.UnregisterCallbacks(IRingActions)" />.
        /// </summary>
        /// <seealso cref="RingActions.UnregisterCallbacks(IRingActions)" />
        public void RemoveCallbacks(IRingActions instance)
        {
            if (m_Wrapper.m_RingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="RingActions.AddCallbacks(IRingActions)" />
        /// <seealso cref="RingActions.RemoveCallbacks(IRingActions)" />
        /// <seealso cref="RingActions.UnregisterCallbacks(IRingActions)" />
        public void SetCallbacks(IRingActions instance)
        {
            foreach (var item in m_Wrapper.m_RingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_RingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="RingActions" /> instance referencing this action map.
    /// </summary>
    public RingActions @Ring => new RingActions(this);

    // CellPhone
    private readonly InputActionMap m_CellPhone;
    private List<ICellPhoneActions> m_CellPhoneActionsCallbackInterfaces = new List<ICellPhoneActions>();
    private readonly InputAction m_CellPhone_Pose;
    /// <summary>
    /// Provides access to input actions defined in input action map "CellPhone".
    /// </summary>
    public struct CellPhoneActions
    {
        private @RayNeoInput m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CellPhoneActions(@RayNeoInput wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CellPhone/Pose".
        /// </summary>
        public InputAction @Pose => m_Wrapper.m_CellPhone_Pose;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CellPhone; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CellPhoneActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CellPhoneActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CellPhoneActions" />
        public void AddCallbacks(ICellPhoneActions instance)
        {
            if (instance == null || m_Wrapper.m_CellPhoneActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CellPhoneActionsCallbackInterfaces.Add(instance);
            @Pose.started += instance.OnPose;
            @Pose.performed += instance.OnPose;
            @Pose.canceled += instance.OnPose;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CellPhoneActions" />
        private void UnregisterCallbacks(ICellPhoneActions instance)
        {
            @Pose.started -= instance.OnPose;
            @Pose.performed -= instance.OnPose;
            @Pose.canceled -= instance.OnPose;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CellPhoneActions.UnregisterCallbacks(ICellPhoneActions)" />.
        /// </summary>
        /// <seealso cref="CellPhoneActions.UnregisterCallbacks(ICellPhoneActions)" />
        public void RemoveCallbacks(ICellPhoneActions instance)
        {
            if (m_Wrapper.m_CellPhoneActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CellPhoneActions.AddCallbacks(ICellPhoneActions)" />
        /// <seealso cref="CellPhoneActions.RemoveCallbacks(ICellPhoneActions)" />
        /// <seealso cref="CellPhoneActions.UnregisterCallbacks(ICellPhoneActions)" />
        public void SetCallbacks(ICellPhoneActions instance)
        {
            foreach (var item in m_Wrapper.m_CellPhoneActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CellPhoneActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CellPhoneActions" /> instance referencing this action map.
    /// </summary>
    public CellPhoneActions @CellPhone => new CellPhoneActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "SimpleTouch" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SimpleTouchActions.AddCallbacks(ISimpleTouchActions)" />
    /// <seealso cref="SimpleTouchActions.RemoveCallbacks(ISimpleTouchActions)" />
    public interface ISimpleTouchActions
    {
        /// <summary>
        /// Method invoked when associated input action "Tap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTap(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPress(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "MulitTouch" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="MulitTouchActions.AddCallbacks(IMulitTouchActions)" />
    /// <seealso cref="MulitTouchActions.RemoveCallbacks(IMulitTouchActions)" />
    public interface IMulitTouchActions
    {
        /// <summary>
        /// Method invoked when associated input action "Touch1Tap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch1Tap(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch2Tap" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch2Tap(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch1Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch1Position(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch2Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch2Position(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch1Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch1Press(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Touch2Press" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouch2Press(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Ring" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="RingActions.AddCallbacks(IRingActions)" />
    /// <seealso cref="RingActions.RemoveCallbacks(IRingActions)" />
    public interface IRingActions
    {
        /// <summary>
        /// Method invoked when associated input action "XRPose" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnXRPose(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPadClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPadClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "HeavyClick" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnHeavyClick(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Rotation" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRotation(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Position" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPosition(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CellPhone" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CellPhoneActions.AddCallbacks(ICellPhoneActions)" />
    /// <seealso cref="CellPhoneActions.RemoveCallbacks(ICellPhoneActions)" />
    public interface ICellPhoneActions
    {
        /// <summary>
        /// Method invoked when associated input action "Pose" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPose(InputAction.CallbackContext context);
    }
}
